<a href="https://colab.research.google.com/github/KA18202005/ML--Learning/blob/main/NLP_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import requests

In [4]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US')

In [5]:
response

In [6]:
temp_df = pd.DataFrame(response.json()['results'])

In [7]:
temp_df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733
5,False,/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",20.6856,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.534,17939
6,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,32.9394,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.526,35158
7,False,/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",6.8195,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.516,4554
8,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,22.6239,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.504,18836
9,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",24.1307,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.495,20118
10,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,31.0738,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.493,26006
11,False,/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg,"[53, 80, 35]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",24.0659,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.486,29664
12,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,21.2082,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.478,12286
13,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,14.7298,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.468,9406
14,False,/8sNiAPPYU14PUepFNeSNGUTiHW.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,47.9132,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.500,38835
15,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,23.8806,/saHP97rTPS5eLmrLQEcANmKrsFl.jpg,1994-06-23,Forrest Gump,False,8.462,29224
16,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",23.4272,/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg,1990-09-12,GoodFellas,False,8.452,13998
17,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,8.6943,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,Seven Samurai,False,8.450,4105
18,False,/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0090,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.443,6348
19,False,/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,9.5895,/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg,1997-12-20,Life Is Beautiful,False,8.440,13778

In [45]:
temp_df.shape

(20, 14)

In [46]:
df = pd.DataFrame()

In [47]:
all_movies = []
for i in range(1,472):
  response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}')
  temp_df = pd.DataFrame(response.json()['results'])
  all_movies.append(temp_df)
  df = pd.concat(all_movies,ignore_index=True)

In [48]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733

In [49]:
df.shape

(9420, 14)

In [50]:
genres_response = requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US')

In [51]:
genres_json = genres_response.json()
print(genres_json)

{'genres': [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 80, 'name': 'Crime'}, {'id': 99, 'name': 'Documentary'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}, {'id': 36, 'name': 'History'}, {'id': 27, 'name': 'Horror'}, {'id': 10402, 'name': 'Music'}, {'id': 9648, 'name': 'Mystery'}, {'id': 10749, 'name': 'Romance'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 10770, 'name': 'TV Movie'}, {'id': 53, 'name': 'Thriller'}, {'id': 10752, 'name': 'War'}, {'id': 37, 'name': 'Western'}]}

In [52]:
genres_df = pd.DataFrame(genres_json['genres'])
genres_df.head()

   id       name
0  28     Action
1  12  Adventure
2  16  Animation
3  35     Comedy
4  80      Crime

In [53]:
df.drop_duplicates(subset=['id'], inplace=True)
print("Duplicates removed from df based on 'id' column.")

Duplicates removed from df based on 'id' column.

In [54]:
def replace_genre_ids(genre_ids_list):
    if isinstance(genre_ids_list, list):
        return [genres_map.get(genre_id, 'Unknown') for genre_id in genre_ids_list]
    return []

df['genre_ids'] = df['genre_ids'].apply(replace_genre_ids)
print("Genre IDs in 'genre_ids' column replaced with genre names again.")

Genre IDs in 'genre_ids' column replaced with genre names again.

In [55]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,The defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733

In [58]:
df['overview'][0]

'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.'

In [60]:
df['overview'] = df['overview'].str.lower()

In [61]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,in the continuing saga of the corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,the true story of how businessman oskar schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,the defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733

In [62]:
import re

In [63]:
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [64]:
remove_html_tags(df['overview'][0])

'imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker andy dufresne begins a new life at the shawshank prison, where he puts his accounting skills to work for an amoral warden. during his long stretch in prison, dufresne comes to be admired by the other inmates -- including an older prisoner named red -- for his integrity and unquenchable sense of hope.'

In [67]:
df['overview'] = df['overview'].apply(remove_html_tags)

In [68]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,in the continuing saga of the corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,the true story of how businessman oskar schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,the defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733

In [69]:
import string

In [70]:
def remove_punctuations(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [71]:
df['overview'].apply(remove_punctuations)

0       imprisoned in the 1940s for the double murder ...
1       spanning the years 1945 to 1955 a chronicle of...
2       in the continuing saga of the corleone crime f...
3       the true story of how businessman oskar schind...
4       the defense and the prosecution have rested an...
                              ...
9415    five people who never met are convened by a no...
9416    a successful physician and devoted family man ...
9417    when former getaway driver charlie bronson jeo...
9418    astronauts search for solutions to save a dyin...
9419    antoine a bachelor partygoer gets new roommate...
Name: overview, Length: 9417, dtype: object

In [72]:
from textblob import TextBlob

In [73]:
df['TextBlob_Overview'] = df['overview'].apply(TextBlob)
print("Created 'TextBlob_Overview' column with TextBlob objects.")

Created 'TextBlob_Overview' column with TextBlob objects.

In [74]:
df['polarity'] = df['TextBlob_Overview'].apply(lambda x: x.sentiment.polarity)
df['subjectivity'] = df['TextBlob_Overview'].apply(lambda x: x.sentiment.subjectivity)
print("Extracted sentiment polarity and subjectivity to new columns.")

Extracted sentiment polarity and subjectivity to new columns.

In [75]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,TextBlob_Overview,polarity,subjectivity
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707,"(i, m, p, r, i, s, o, n, e, d, , i, n, , t, ...",0.021338,0.260480
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437,"(s, p, a, n, n, i, n, g, , t, h, e, , y, e, ...",-0.250000,0.416667
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,in the continuing saga of the corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578,"(i, n, , t, h, e, , c, o, n, t, i, n, u, i, ...",0.118182,0.427273
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,the true story of how businessman oskar schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095,"(t, h, e, , t, r, u, e, , s, t, o, r, y, , ...",0.175000,0.325000
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,the defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733,"(t, h, e, , d, e, f, e, n, s, e, , a, n, d, ...",-0.005000,0.595000

In [76]:
import nltk

In [77]:
from nltk.corpus import stopwords

In [78]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return " ".join(filtered_words)

In [82]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,TextBlob_Overview,polarity,subjectivity,overview_no_stopwords
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707,"(i, m, p, r, i, s, o, n, e, d, , i, n, , t, ...",0.021338,0.260480,"imprisoned 1940s double murder wife lover, ups..."
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437,"(s, p, a, n, n, i, n, g, , t, h, e, , y, e, ...",-0.250000,0.416667,"spanning years 1945 1955, chronicle fictional ..."
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,in the continuing saga of the corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578,"(i, n, , t, h, e, , c, o, n, t, i, n, u, i, ...",0.118182,0.427273,"continuing saga corleone crime family, young v..."
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,the true story of how businessman oskar schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095,"(t, h, e, , t, r, u, e, , s, t, o, r, y, , ...",0.175000,0.325000,true story businessman oskar schindler saved t...
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,the defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733,"(t, h, e, , d, e, f, e, n, s, e, , a, n, d, ...",-0.005000,0.595000,defense prosecution rested jury filing jury ro...

In [81]:
import nltk
nltk.download('stopwords')
df['overview_no_stopwords'] = df['overview'].apply(remove_stopwords)
print("Stop words removed and stored in 'overview_no_stopwords' column.")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

Stop words removed and stored in 'overview_no_stopwords' column.

In [80]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,TextBlob_Overview,polarity,subjectivity
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707,"(i, m, p, r, i, s, o, n, e, d, , i, n, , t, ...",0.021338,0.260480
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437,"(s, p, a, n, n, i, n, g, , t, h, e, , y, e, ...",-0.250000,0.416667
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,in the continuing saga of the corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578,"(i, n, , t, h, e, , c, o, n, t, i, n, u, i, ...",0.118182,0.427273
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,the true story of how businessman oskar schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095,"(t, h, e, , t, r, u, e, , s, t, o, r, y, , ...",0.175000,0.325000
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,the defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733,"(t, h, e, , d, e, f, e, n, s, e, , a, n, d, ...",-0.005000,0.595000

In [83]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
print("Imported WordNetLemmatizer and downloaded 'wordnet' corpus.")

[nltk_data] Downloading package wordnet to /root/nltk_data...

Imported WordNetLemmatizer and downloaded 'wordnet' corpus.

In [84]:
lemmatizer = WordNetLemmatizer()
def lemmatize_text(text):
    words = text.split() # Simple tokenization by splitting on space
    lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(lemmatized_words)
df['overview_lemmatized'] = df['overview'].apply(lemmatize_text)
print("Lemmatization applied to 'overview' column and stored in 'overview_lemmatized'.")

Lemmatization applied to 'overview' column and stored in 'overview_lemmatized'.

In [85]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,TextBlob_Overview,polarity,subjectivity,overview_no_stopwords,overview_lemmatized
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707,"(i, m, p, r, i, s, o, n, e, d, , i, n, , t, ...",0.021338,0.260480,"imprisoned 1940s double murder wife lover, ups...",imprisoned in the 1940s for the double murder ...
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437,"(s, p, a, n, n, i, n, g, , t, h, e, , y, e, ...",-0.250000,0.416667,"spanning years 1945 1955, chronicle fictional ...","spanning the year 1945 to 1955, a chronicle of..."
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,in the continuing saga of the corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578,"(i, n, , t, h, e, , c, o, n, t, i, n, u, i, ...",0.118182,0.427273,"continuing saga corleone crime family, young v...",in the continuing saga of the corleone crime f...
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,the true story of how businessman oskar schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095,"(t, h, e, , t, r, u, e, , s, t, o, r, y, , ...",0.175000,0.325000,true story businessman oskar schindler saved t...,the true story of how businessman oskar schind...
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,the defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733,"(t, h, e, , d, e, f, e, n, s, e, , a, n, d, ...",-0.005000,0.595000,defense prosecution rested jury filing jury ro...,the defense and the prosecution have rested an...

In [86]:
from nltk.stem import PorterStemmer
import nltk
nltk.download('punkt')
stemmer = PorterStemmer()
print("PorterStemmer imported and instantiated. 'punkt' tokenizer downloaded.")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

PorterStemmer imported and instantiated. 'punkt' tokenizer downloaded.

In [87]:
def stem_text(text):
    words = text.split() # Simple tokenization by splitting on space
    stemmed_words = [stemmer.stem(word) for word in words]
    return " ".join(stemmed_words)
df['overview_stemmed'] = df['overview'].apply(stem_text)
print("Stemming applied to 'overview' column and stored in 'overview_stemmed'.")

Stemming applied to 'overview' column and stored in 'overview_stemmed'.

In [88]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,TextBlob_Overview,polarity,subjectivity,overview_no_stopwords,overview_lemmatized,overview_stemmed
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[Drama, Crime]",278,en,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,35.6691,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.715,29707,"(i, m, p, r, i, s, o, n, e, d, , i, n, , t, ...",0.021338,0.260480,"imprisoned 1940s double murder wife lover, ups...",imprisoned in the 1940s for the double murder ...,imprison in the 1940 for the doubl murder of h...
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[Drama, Crime]",238,en,The Godfather,"spanning the years 1945 to 1955, a chronicle o...",37.7831,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22437,"(s, p, a, n, n, i, n, g, , t, h, e, , y, e, ...",-0.250000,0.416667,"spanning years 1945 1955, chronicle fictional ...","spanning the year 1945 to 1955, a chronicle of...","span the year 1945 to 1955, a chronicl of the ..."
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[Drama, Crime]",240,en,The Godfather Part II,in the continuing saga of the corleone crime f...,22.6171,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13578,"(i, n, , t, h, e, , c, o, n, t, i, n, u, i, ...",0.118182,0.427273,"continuing saga corleone crime family, young v...",in the continuing saga of the corleone crime f...,in the continu saga of the corleon crime famil...
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[Drama, History, War]",424,en,Schindler's List,the true story of how businessman oskar schind...,19.4581,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17095,"(t, h, e, , t, r, u, e, , s, t, o, r, y, , ...",0.175000,0.325000,true story businessman oskar schindler saved t...,the true story of how businessman oskar schind...,the true stori of how businessman oskar schind...
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[Drama],389,en,12 Angry Men,the defense and the prosecution have rested an...,14.4071,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9733,"(t, h, e, , d, e, f, e, n, s, e, , a, n, d, ...",-0.005000,0.595000,defense prosecution rested jury filing jury ro...,the defense and the prosecution have rested an...,the defens and the prosecut have rest and the ...

In [90]:
df[['overview', 'overview_lemmatized', 'overview_stemmed', 'overview_no_stopwords']].head()

,overview,overview_lemmatized,overview_stemmed,overview_no_stopwords
0,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprison in the 1940 for the doubl murder of h...,"imprisoned 1940s double murder wife lover, ups..."
1,"spanning the years 1945 to 1955, a chronicle o...","spanning the year 1945 to 1955, a chronicle of...","span the year 1945 to 1955, a chronicl of the ...","spanning years 1945 1955, chronicle fictional ..."
2,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continu saga of the corleon crime famil...,"continuing saga corleone crime family, young v..."
3,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true stori of how businessman oskar schind...,true story businessman oskar schindler saved t...
4,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defens and the prosecut have rest and the ...,defense prosecution rested jury filing jury ro...