<a href="https://colab.research.google.com/github/KA18202005/ML--Learning/blob/main/NLP_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
missing_values = df[['review', 'sentiment']].isnull().sum()
print("Missing values in 'review' and 'sentiment' columns:\n", missing_values)

Missing values in 'review' and 'sentiment' columns:
 review       0
sentiment    0
dtype: int64

In [5]:
df['review'] = df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [6]:
import re
def remove_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
df['review'] = df['review'].apply(remove_html)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [7]:
def remove_punc_special(text):
    clean = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return clean
df['review'] = df['review'].apply(remove_punc_special)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [8]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Download NLTK data (if not already downloaded)
nltk.download('punkt')
nltk.download('stopwords')

print("NLTK word_tokenize and stopwords imported, and data downloaded.")

NLTK word_tokenize and stopwords imported, and data downloaded.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [9]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Download NLTK data (if not already downloaded)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Explicitly downloading punkt_tab as suggested by the error

print("NLTK word_tokenize and stopwords imported, and data downloaded.")

NLTK word_tokenize and stopwords imported, and data downloaded.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [10]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Get the list of English stopwords
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    # Tokenize the text
    tokens = word_tokenize(text)
    # Remove stopwords
    filtered_tokens = [word for word in tokens if word not in stop_words]
    # Join the filtered tokens back into a string
    return ' '.join(filtered_tokens)

# Apply the function to the 'review' column
df['review'] = df['review'].apply(remove_stopwords)

# Display the first few rows of the DataFrame to verify the changes
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [11]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    tokens = word_tokenize(text)
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(lemmatized_tokens)

df['review'] = df['review'].apply(lemmatize_text)

df.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

                                              review sentiment
0  one reviewer mentioned watching 1 oz episode y...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there family little boy jake think t...  negative
4  petter matteis love time money visually stunni...  positive

In [12]:
df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})
print(df['sentiment'].value_counts())
df.head()

sentiment
1    25000
0    25000
Name: count, dtype: int64

                                              review  sentiment
0  one reviewer mentioned watching 1 oz episode y...          1
1  wonderful little production filming technique ...          1
2  thought wonderful way spend time hot summer we...          1
3  basically there family little boy jake think t...          0
4  petter matteis love time money visually stunni...          1

In [13]:
all_words = ' '.join(df['review']).split()
total_words = len(all_words)
unique_words = len(set(all_words))

print(f"Total number of words in the corpus: {total_words}")
print(f"Total number of unique words (vocabulary) in the corpus: {unique_words}")

Total number of words in the corpus: 5988641
Total number of unique words (vocabulary) in the corpus: 210405

In [14]:
df['positive_sentiment'] = df['sentiment'].apply(lambda x: 1 if x == 1 else 0)
df['negative_sentiment'] = df['sentiment'].apply(lambda x: 1 if x == 0 else 0)

df = df.drop('sentiment', axis=1)

print(df[['positive_sentiment', 'negative_sentiment']].head())
df.head()

   positive_sentiment  negative_sentiment
0                   1                   0
1                   1                   0
2                   1                   0
3                   0                   1
4                   1                   0

,review,positive_sentiment,negative_sentiment
0,one reviewer mentioned watching 1 oz episode y...,1,0
1,wonderful little production filming technique ...,1,0
2,thought wonderful way spend time hot summer we...,1,0
3,basically there family little boy jake think t...,0,1
4,petter matteis love time money visually stunni...,1,0

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=1, stop_words=None)

In [16]:
X = vectorizer.fit_transform(df['review'])

In [17]:
vocabulary = vectorizer.get_feature_names_out()

In [18]:
import pandas as pd

# Sum the occurrences of each word across all documents (axis=0) directly from the sparse matrix X
total_occurrences = X.sum(axis=0)

# Convert the result to a dense array and then to a pandas Series
word_counts = pd.Series(total_occurrences.tolist()[0], index=vocabulary)

print(f"Vocabulary size: {len(vocabulary)}")
print("\nFirst 10 words in vocabulary:", vocabulary[:10])
print("\nShape of the word counts matrix (number of reviews x vocabulary size):", X.shape)

print("\nTop 20 most frequent words and their total occurrences:")
display(word_counts.sort_values(ascending=False).head(20))

Vocabulary size: 210371

First 10 words in vocabulary: ['00' '000' '0000000000001' '00000001' '000001' '0001' '00015' '001'
 '0010' '002']

Shape of the word counts matrix (number of reviews x vocabulary size): (50000, 210371)

Top 20 most frequent words and their total occurrences:

movie        98939
film         89753
one          52649
like         39781
time         29356
good         28596
character    27567
get          24432
even         24282
story        24212
would        24001
make         23563
see          23489
really       22894
scene        20696
much         18895
well         18615
people       17973
great        17799
bad          17646
dtype: int64

### Bag of Bi-grams (n-gram range 1-2)

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer for unigrams and bi-grams
vectorizer_bigram = CountVectorizer(ngram_range=(1, 2), min_df=1, stop_words=None)

# Fit and transform the 'review' column
X_bigram = vectorizer_bigram.fit_transform(df['review'])

# Get the feature names (vocabulary)
vocabulary_bigram = vectorizer_bigram.get_feature_names_out()

print(f"Vocabulary size for unigrams + bi-grams: {len(vocabulary_bigram)}")
print("\nFirst 20 words/bi-grams in vocabulary:", vocabulary_bigram[:20])
print("\nShape of the bi-gram word counts matrix (number of reviews x vocabulary size):", X_bigram.shape)

Vocabulary size for unigrams + bi-grams: 3320943

First 20 words/bi-grams in vocabulary: ['00' '00 acting' '00 agent' '00 come' '00 including' '00 schneider'
 '00 worth' '000' '000 000' '000 overboard' '000 produce' '0000000000001'
 '0000000000001 10' '00000001' '00000001 population' '000001'
 '000001 chance' '0001' '0001 percent' '00015']

Shape of the bi-gram word counts matrix (number of reviews x vocabulary size): (50000, 3320943)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer for unigrams, bi-grams, and tri-grams
vectorizer_trigram = CountVectorizer(ngram_range=(1, 3), min_df=1, stop_words=None)

# Fit and transform the 'review' column
X_trigram = vectorizer_trigram.fit_transform(df['review'])

# Get the feature names (vocabulary)
vocabulary_trigram = vectorizer_trigram.get_feature_names_out()

print(f"Vocabulary size for unigrams + bi-grams + tri-grams: {len(vocabulary_trigram)}")
print("\nFirst 20 words/n-grams in vocabulary:", vocabulary_trigram[:20])
print("\nShape of the tri-gram word counts matrix (number of reviews x vocabulary size):", X_trigram.shape)

Vocabulary size for unigrams + bi-grams + tri-grams: 8733966

First 20 words/n-grams in vocabulary: ['00' '00 acting' '00 acting character' '00 agent' '00 agent difficult'
 '00 agent level' '00 come' '00 come back' '00 including'
 '00 including unusual' '00 schneider' '00 schneider directly'
 '00 schneider murderervillain' '00 worth' '00 worth film' '000' '000 000'
 '000 000 overboard' '000 overboard' '000 produce']

Shape of the tri-gram word counts matrix (number of reviews x vocabulary size): (50000, 8733966)

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(min_df=1, stop_words=None)

# Fit and transform the 'review' column
X_tfidf = tfidf_vectorizer.fit_transform(df['review'])

# Get the feature names (vocabulary)
tfidf_vocabulary = tfidf_vectorizer.get_feature_names_out()

# Get the IDF scores
idf_scores = tfidf_vectorizer.idf_

In [22]:
tfidf_vocabulary

array(['00', '000', '0000000000001', ..., 'zzzzzzzzzzzzz',
       'zzzzzzzzzzzzzzzzzz', 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'],
      dtype=object)

In [23]:
idf_scores

array([ 9.87388814, 10.721186  , 11.1266511 , ..., 11.1266511 ,
       11.1266511 , 11.1266511 ])